name: Deploy LAMP Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

          script: |
            echo "🚀 Connected to EC2 Server"

            cd /var/www/html

            echo "📥 Pulling latest code..."
            git pull origin main

            echo "🔄 Restart Apache..."
            sudo systemctl restart apache2

            echo "✅ Deployment Successful!"
